properties:
  environmentId: "/subscriptions/1d7f1b24-3cc5-453c-a65e-967a617536b9/resourceGroups/BritEdge_DEV_RG/providers/Microsoft.App/managedEnvironments/container-app-env-britedge"
  configuration:
    ingress:
      external: true
      targetPort: 8080
    activeRevisionsMode: Single

    secrets:
    - name: cosmos-key
      keyVaultUrl: https://britedge-keyvault-gg.vault.azure.net/secrets/cosmos-key/5ef361b12f1b4deb930d5389e8673093
      identity: system

    - name: cosmos-endpoint
      keyVaultUrl: https://britedge-keyvault-gg.vault.azure.net/secrets/cosmos-endpoint/939cc0f3d2874b8f87c92e43d3f26620
      identity: system

  templates:
    conatiners:
      - name: jobschedule-webapp
        image: britedgeregistry.azurecr.io/britedgejobapp1:latest
        resources:
          cpu: 0.25
          memory: 0.5Gi
        env:
          - name: COSMOS-KEY
            secretRef: cosmos-key
          - name: COSMOS-ENDPOINT
            secretRef: cosmos-endpoint
tags:
  Environment: Dev
  Service: Container App

identity:
  type: SystemAssigned

