name: Main Az_login Auto-Deploy container-app-britedge

# When this action will be executed
on:
    # Automatically trigger it when detected changes in repo
    # push:
    #     branches: [main]
    #     paths:
    #         - "**"
    #         - ".github/workflows/az-cli_container-app-britedge-AutoDeployTrigger-a0e30be8-1cc7-4062-ae12-d5e0121470d1_v3.yml"

    # Allow manual trigger
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.CONTAINERAPPBRITEDGE_AZURE_CREDENTIALS }}

            - name: Docker login to ACR
              uses: azure/docker-login@v1
              with:
                  login-server: BritEdgeRegistry.azurecr.io
                  username: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_USERNAME }}
                  password: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_PASSWORD }}

            - name: Build and push image
              run: |
                  docker build -t BritEdgeRegistry.azurecr.io/britedgejobapp1:latest .
                  docker push BritEdgeRegistry.azurecr.io/britedgejobapp1:latest
            
            # Creates new container app after image is pushed to ACR
            - name: Update Container App Registry
              uses: azure/container-apps-deploy-action@v2
              with:
                appSourcePath: .
                registryUrl: britedgeregistry.azurecr.io
                registryUsername: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_USERNAME }}
                registryPassword: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_PASSWORD }}
                containerAppName: container-app-britedge
                resourceGroup: BritEdge_DEV_RG
                imageToDeploy: britedgeregistry.azurecr.io/britedgejobapp1:latest

            # - name: Update Container App image
            #   run: |
            #       az containerapp update \
            #         --name container-app-britedge \
            #         --resource-group BritEdge_DEV_RG \
            #         --image BritEdgeRegistry.azurecr.io/britedgejobapp1:latest