name: Main Az_login Auto-Deploy container-app-britedge

# When this action will be executed
on:
    # Automatically trigger it when detected changes in repo
    # push:
    #     branches: [main]
    #     paths:
    #         - "**"
    #         - ".github/workflows/az-cli_container-app-britedge-AutoDeployTrigger-a0e30be8-1cc7-4062-ae12-d5e0121470d1_v3.yml"

    # Allow manual trigger
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.CONTAINERAPPBRITEDGE_AZURE_CREDENTIALS }}

            - name: Docker login to ACR
              uses: azure/docker-login@v1
              with:
                  login-server: britedgejobapp1.azurecr.io
                  username: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_USERNAME }}
                  password: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_PASSWORD }}

            - name: Build and push image
              run: |
                  docker build -t britedgejobapp1.azurecr.io/britedgejobapp1:${{ github.sha }} .
                  docker push britedgejobapp1.azurecr.io/britedgejobapp1:${{ github.sha }}

            - name: Update Container App image
              run: |
                  az containerapp update \
                    --name container-app-britedge \
                    --resource-group BritEdge_DEV_RG \
                    --image britedgejobapp1.azurecr.io/britedgejobapp1:${{ github.sha }}
