name: Step 2 - Push and Deploy Image to Container App

# When this action will be executed
on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.CONTAINERAPPBRITEDGE_AZURE_CREDENTIALS }}

            - name: Docker login to ACR
              uses: azure/docker-login@v1
              with:
                  login-server: BritEdgeRegistry.azurecr.io
                  username: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_USERNAME }}
                  password: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_PASSWORD }}

            - name: Build and push image to ACR
              run: |
                  docker build -t BritEdgeRegistry.azurecr.io/britedgejobapp1:latest .
                  docker push BritEdgeRegistry.azurecr.io/britedgejobapp1:latest
            
            # Creates new container app after image is pushed to ACR
            - name: Deploy Container App 
              uses: azure/container-apps-deploy-action@v2
              with:
                appSourcePath: .
                # ACR
                registryUrl: britedgeregistry.azurecr.io
                registryUsername: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_USERNAME }}
                registryPassword: ${{ secrets.CONTAINERAPPBRITEDGE_REGISTRY_PASSWORD }}
                # Container App
                containerAppName: container-app-britedge
                resourceGroup: BritEdge_DEV_RG
                imageToDeploy: 
                #YAML for extra configs
                yamlConfigPath: .github/containerapp.yml


